name: LogLint

on:
  push:
  pull_request:

jobs:
  loglint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - run: go mod tidy

      - name: Test loglint
        run: go test .\... -v

      - name: Build loglint
        run: go build -o loglint ./cmd/loglint

      - name: Run loglint
        run: ./loglint ./testdata/example.go
