name: LogLint

on:
  push:
  pull_request:

jobs:
  loglint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: Test loglint
        run: go test ./... -v

      - name: Build loglint
        run: go build -o loglint ./cmd/loglint

